### ISSUE TITLE
Hosts Details - Notifications

### ISSUE THREAD

**Issue by rcmaiolini** [ercole-io/ercole-web#126]
@raffaelloferrari 

Ciao,

d'accordo con la imagine, come sarebbe diviso il risultato che ricevo della API nelle 3 categorie, Agents, LIcenses e Systems? 
E cosa intende "notifications from the last week"?

![DeepinScreenshot_select-area_20200608104333](https://user-images.githubusercontent.com/9290357/84037543-1d88e500-a975-11ea-9dde-db0341ad5f02.png)

Grazie

**Comment by cirelli94** [comment]
Duplicate of https://github.com/ercole-io/ercole-web/issues/165
