### ISSUE TITLE
Dashboard: technologies

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-web#131]
We must use the api as changed from https://github.com/ercole-io/ercole/issues/239 to the technologies component of dashboard.

We must add a circular progress bar around percentual value of the color of the icon ( from https://github.com/ercole-io/ercole/issues/240 ).

**Comment by rcmaiolini** [comment]
It is done, but for the moment the colors and logos don't come from API.
The colors for now is generate by random function.
