### ISSUE TITLE
Dashboard Alerts

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-web#133]
In the dashboard there must be 3 panels, one for each category:
- AGENT -> Agent (icon: broadcast-tower)
- LICENSE -> License (icon: dollar-sing)
- ENGINE -> Ercole Engine (icon: tools)

Each panel represent a deck of alerts; inside the deck they are sorted with these criteria:

1. severity: `warning` and `critical` first, then `info`
2. date: newest first

License and Engine panels has a "Mark as read" button, that mark as read only that single alert (calling  `/alerts/{id}` ), and show the next alert (following above criteria).

For each little panel there must be three numbers under it, which is the number of alert of that panel category for each severity (`info` / `warn` / `critical`).
They must be clickable: once clicked they must route user to alerts page filtered by that severity and category code.

If there are no alerts for a category, it must be an empty alert with a message: "There are no [ Agent / License / Ercole Engine ] alerts"

Here a mockup:

![image](https://user-images.githubusercontent.com/1636493/85543590-7f567980-b61a-11ea-92f1-ce134aeb0143.png)

**Comment by cirelli94** [comment]
Actually, severities are: `NOTICE, MINOR, MAJOR, CRITICAL, WARNING` !
info / warn / critical -> ?????????

**Comment by cirelli94** [comment]
Depends on https://github.com/ercole-io/ercole/issues/252

**Comment by cirelli94** [comment]
What should do Agent panel when open "Inspect" button?
Open Hosts with the list of agents stopped?

**Comment by rcmaiolini** [comment]
The feature is almost complete. Is missing
