### ISSUE TITLE
Add Hosts page

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-web#137]
We must add an "Hosts" page to show the list of hosts returned from a call to `/hosts` with the selected filters.

We must have a button to open a panel/window/section for filters, which normally must be hidden.
We must have all filters allowed from the `/hosts` api (take a look at https://github.com/ercole-io/ercole/blob/master/swagger.yml ).
All filters allow empty value.

---

At the bottom of the page we must have two buttons:
- [ ] `Export data` that call `/hosts` with the active filters and with Header set to `Accept=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` and save output file.
- [ ] `LMS audit file `that call `/hosts` with the active filters and with Header set to `application/vnd.oracle.lms+vnd.openxmlformats-officedocument.spreadsheetml.sheet` and save output file.

Here an example with cURL:
```
curl --location --request GET 'http://dev.ercole.io/api/hosts' \
--header 'Accept: application/vnd.oracle.lms+vnd.openxmlformats-officedocument.spreadsheetml.sheet' \
--header 'Authorization: Basic dXNlcjpwYXNzd29yZA=='
```

**Comment by amreo** [comment]
For Host List File and LMS audit file the parameter mode is not required but it's required to set Content-Type to application/vnd.openxmlformats-officedocument.spreadsheetml.sheet or application/vnd.oracle.lms+vnd.openxmlformats-officedocument.spreadsheetml.sheet
