### ISSUE TITLE
Alerts Page - Change Mark as read Column

### ISSUE THREAD

**Issue by rcmaiolini** [ercole-io/ercole-web#162]
aggiungere i checkbox per selezionare
un checkbox in alto che seleziona tutta la colonna
un checkbox seleziona tutti gli elementi
quando i checkbox sono selezionati compare un bottone Mark checked as read
aggiungere filtro data

**Comment by cirelli94** [comment]
When all alerts on a page are selected, we must show a message like:
`Tutte le 50 conversazioni in questa pagina sono state selezionate. Seleziona tutte le 1.448 conversazioni in Posta inviata
`All the 50 alerts in this page are selected. **Select all the 1.433 alerts**`
Where **Select all the 1.433 alerts** is clickable and select all the alerts.
