### ISSUE TITLE
Add Database List page

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-web#174]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
Add Database List page
using https://github.com/ercole-io/ercole/issues/341 api

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by amreo** [comment]
It's not completed. The page is using oracle-specific APIs

**Comment by amreo** [comment]
Depends on https://github.com/ercole-io/ercole/issues/341
