### ISSUE TITLE
[BUG] Patch Advisor page: wrong periods checks

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-web#198]
**Describe the bug**
Values of 4-6-12 months are wrong!
We must compare today with "Release date"

We must use some icons like a green check and a red cross to show this information, like the old ones:
![image](https://user-images.githubusercontent.com/1636493/90372837-50d0aa00-e071-11ea-85c6-8a87d6901293.png)

If Release date is 1/1/1970 do not show the date but instead "---"

**Expected behavior**
Correct comparison between release date and today

**Comment by raffaelloferrari** [comment]
Column Release date of table show api value of "createdAt" instead of "date". 
Accordingly value of 4 6 12 Month are wrong.

**Comment by raffaelloferrari** [comment]
@cirelli94 
Can you move this Issue on Sprint6?
