### ISSUE TITLE
Host list: show type of cluster

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-web#201]
**Is your feature request related to a problem? Please describe.**
We need to know which kind of cluster an host is.

**Describe the solution you'd like**
Add column "Cluster type"

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by cirelli94** [comment]
Investigate API

**Comment by amreo** [comment]
HardwareAbstractionTechnology?

**Comment by cirelli94** [comment]
@raffaelloferrari Cluster Type value is the HardwareAbstractionTechnology value from host.sh fetcher?
