### ISSUE TITLE
Add the page for viewing the list of agreements

### ISSUE THREAD

**Issue by amreo** [ercole-io/ercole-web#210]
**Is your feature request related to a problem? Please describe.**
I want to see the list of agreement I've added to ercole 

**Describe the solution you'd like**
I want that ercole have a page like to this mock.
![Schermata del 2020-08-25 13-41-12](https://user-images.githubusercontent.com/12671924/91170102-a68ffc80-e6d8-11ea-9d08-fbc0254f69f9.png)

**Describe alternatives you've considered**
Use ercole by command line interaface.

**Additional context**
Only Oracle/Database agreements menu should be supported now.
The API for getting the list of Oracle/Database aggreement is `GET /agreements/oracle/database` (https://github.com/ercole-io/ercole/issues/371).
The list of hosts for autocomplete can be obtained by `GET /hosts?mode=summary&cluster=NULL`.
The list of CSI, Metrics, Reference Number, Agreement number can be computed by looping throught the agreements.
When the user click to underlined host or to the edit button, the list of hostnames is shown.
When the user click to the trash button, the agreement is deleted by calling the API `DELETE /agreements/oracle/database/{id}` (https://github.com/ercole-io/ercole/issues/370).
When the user click to the host trash button, the association is deleted by calling the API `DELETE /agreements/oracle/database/{id}/hosts/{hostname}` (https://github.com/ercole-io/ercole/issues/369).
When the user select a suggested host, the association is added by calling the API `POST /agreements/oracle/database/{id}/hosts` (https://github.com/ercole-io/ercole/issues/368).
The number of "Number licenses used" can be obtained from **coveredLicensesCount**

**Comment by cirelli94** [comment]
@rcmaiolini 
The list of hosts for autocomplete must be obtained by GET '/hosts?mode=summary&cluster=NULL'.
There are some hosts proposed by the autocomplete now that have clusters.
