### ISSUE TITLE
Add the possibility to add agreements

### ISSUE THREAD

**Issue by amreo** [ercole-io/ercole-web#211]
**Is your feature request related to a problem? Please describe.**
I want to add a agreement to my agreements collection.
 
**Describe the solution you'd like**
I want that the right form in the mock is added to the right of the agreement page with the "ADD A LICENSES" ("ADD A AGREEMENT"?) button.

**Describe alternatives you've considered**
Use ercole CLI.

**Additional context**
![Schermata del 2020-08-24 17-27-04](https://user-images.githubusercontent.com/12671924/91413482-76b53600-e84b-11ea-89a7-78243fbd9ca3.png)
There is a error in the mock: the CSI should not have the select list.
The API for adding agreement is `POST /agreements/oracle/database` (https://github.com/ercole-io/ercole/issues/371)

**Comment by cirelli94** [comment]
We need to enable selection of multiple part ids.
`/agreements/oracle/database` accept an array for them.
