### ISSUE TITLE
Add licenses chart in Dashboard

### ISSUE THREAD

**Issue by raffaelloferrari** [ercole-io/ercole-web#218]
For the first version of ercole 2.0 we have to add a chart to the dashboard that describe the numbers of licenses used and purchased for each type of license.

The type of license can be selected by a select box in top right chart.
Select box contains the same list that we can find in the select box "Part Number, Item Description and Metrics" of agreement page.

Data that must be shown:
On the x --> Time 
On the y --> two lines:
- the number of license used 
- the number of license purchased

Attacched example. 
![Example](https://user-images.githubusercontent.com/47225245/92743291-b36f4a00-f380-11ea-9b24-d92d1d6fbbd3.png)

**Comment by rcmaiolini** [comment]
Sample to create the dashboard chart api:

[
	{
		"partID": "L10001",
		"itemDescription": "Oracle Database Enterprise Edition",
		"metrics": "Named User Plus Perpetual",
		"history": [
			{
				"date": "2020-09-19T15:44:48.418046973+02:00",
				"usedLicenses": 76,
				"purchasedLicenses": 125
			},
			{
				"date": "2020-09-20T15:44:48.418046973+02:00",
				"usedLicenses": 70,
				"purchasedLicenses": 125
			},
			{
				"date": "2020-09-21T15:44:48.418046973+02:00",
				"usedLicenses": 66,
				"purchasedLicenses": 125
			},
			{
				"date": "2020-09-22T15:44:48.418046973+02:00",
				"usedLicenses": 69,
				"purchasedLicenses": 125
			},
			{
				"date": "2020-09-23T15:44:48.418046973+02:00",
				"usedLicenses": 67,
				"purchasedLicenses": 125
			},
			{
				"date": "2020-09-24T15:44:48.418046973+02:00",
				"usedLicenses": 61,
				"purchasedLicenses": 125
			},
			{
				"date": "2020-09-25T15:44:48.418046973+02:00",
				"usedLicenses": 54,
				"purchasedLicenses": 125
			},
			{
				"date": "2020-09-26T15:44:48.418046973+02:00",
				"usedLicenses": 61,
				"purchasedLicenses": 125
			},
			{
				"date": "2020-09-27T15:44:48.418046973+02:00",
				"usedLicenses": 55,
				"purchasedLicenses": 125
			},
			{
				"date": "2020-09-28T15:44:48.418046973+02:00",
				"usedLicenses": 60,
				"purchasedLicenses": 125
			}
		]
	},
	{
		"partID": "L103399",
		"itemDescription": "Oracle Database Standard Edition 2",
		"metrics": "Processor Perpetual",
		"history": [
			{
				"date": "2020-09-19T15:44:48.418046973+02:00",
				"usedLicenses": 96,
				"purchasedLicenses": 25
			},
			{
				"date": "2020-09-20T15:44:48.418046973+02:00",
				"usedLicenses": 94,
				"purchasedLicenses": 75
			},
			{
				"date": "2020-09-21T15:44:48.418046973+02:00",
				"usedLicenses": 98,
				"purchasedLicenses": 125
			},
			{
				"date": "2020-09-22T15:44:48.418046973+02:00",
				"usedLicenses": 97,
				"purchasedLicenses": 125
			},
			{
				"date": "2020-09-23T15:44:48.418046973+02:00",
				"usedLicenses": 98,
				"purchasedLicenses": 125
			},
			{
				"date": "2020-09-24T15:44:48.418046973+02:00",
				"usedLicenses": 104,
				"purchasedLicenses": 125
			},
			{
				"date": "2020-09-25T15:44:48.418046973+02:00",
				"usedLicenses": 109,
				"purchasedLicenses": 125
			},
			{
				"date": "2020-09-26T15:44:48.418046973+02:00",
				"usedLicenses": 109,
				"purchasedLicenses": 125
			},
			{
				"date": "2020-09-27T15:44:48.418046973+02:00",
				"usedLicenses": 109,
				"purchasedLicenses": 125
			},
			{
				"date": "2020-09-28T15:44:48.418046973+02:00",
				"usedLicenses": 115,
				"purchasedLicenses": 125
			}
		]
	},
	{
		"partID": "A90611",
		"itemDescription": "Oracle Database Enterprise Edition",
		"metrics": "Processor Perpetual",
		"history": [
			{
				"date": "2020-09-19T15:44:48.418046973+02:00",
				"usedLicenses": 84,
				"purchasedLicenses": 0
			},
			{
				"date": "2020-09-20T15:44:48.418046973+02:00",
				"usedLicenses": 79,
				"purchasedLicenses": 50
			},
			{
				"date": "2020-09-21T15:44:48.418046973+02:00",
				"usedLicenses": 81,
				"purchasedLicenses": 100
			},
			{
				"date": "2020-09-22T15:44:48.418046973+02:00",
				"usedLicenses": 86,
				"purchasedLicenses": 100
			},
			{
				"date": "2020-09-23T15:44:48.418046973+02:00",
				"usedLicenses": 80,
				"purchasedLicenses": 100
			},
			{
				"date": "2020-09-24T15:44:48.418046973+02:00",
				"usedLicenses": 73,
				"purchasedLicenses": 100
			},
			{
				"date": "2020-09-25T15:44:48.418046973+02:00",
				"usedLicenses": 72,
				"purchasedLicenses": 100
			},
			{
				"date": "2020-09-26T15:44:48.418046973+02:00",
				"usedLicenses": 78,
				"purchasedLicenses": 100
			},
			{
				"date": "2020-09-27T15:44:48.418046973+02:00",
				"usedLicenses": 81,
				"purchasedLicenses": 100
			},
			{
				"date": "2020-09-28T15:44:48.418046973+02:00",
				"usedLicenses": 78,
				"purchasedLicenses": 100
			}
		]
	}
]
