### ISSUE TITLE
 Oracle list: add columns Pluggable and Services

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-web#241]
**Is your feature request related to a problem? Please describe.**
Add info in list page.

**Describe the solution you'd like**
And add new columns:
Pluggable (boolean)
Services

**Describe alternatives you've considered**
None

**Additional context**
Depends on https://github.com/ercole-io/ercole/issues/355

**Comment by anbrenna** [comment]
This issue has been divided into ercole-io/ercole-web#403 and ercole-io/ercole-web#404.
