### ISSUE TITLE
Hosts Page > Host details

### ISSUE THREAD

**Issue by andreafurla** [ercole-io/ercole-web#279]
UI
follow the design

![Schermata 2021-03-22 alle 11 35 09](https://user-images.githubusercontent.com/19222614/113690646-ee91eb80-96cb-11eb-83f2-b9ff3518e5b3.png)

**Comment by anbrenna** [comment]
Verify these issues:
- the text in the upper box section (General Info, OS Details, ...) must be left aligned
- the database info section must have 3 columns and data column values must be left aligned
- try to enlarge the height of the graph in order to be aligned with the sections on its  left
