### ISSUE TITLE
Databases Page

### ISSUE THREAD

**Issue by andreafurla** [ercole-io/ercole-web#280]
UI
follow the design

![Schermata 2021-03-22 alle 15 45 33](https://user-images.githubusercontent.com/19222614/113690819-1d0fc680-96cc-11eb-8a8b-bd081b1c2926.png)

Also (like the filters buttons of the "Hosts page"):
- group Archivelog Mode, DR and HA in a block colums and show it after click on a button called "Reliability";

UX
As a user when I view the table, If I click on Show more info: RELIABILITY, then I must be able to view all related columns straight after the first column "DB Name".
The first columns db name will always be fixed,
While the other columns will be dynamically displayed based on the selected button Show more

**Comment by anbrenna** [comment]
Archivelog Mode, DR and HA columns will be dynamically displayed or not (toggle) with a button "Reliability", See the Oracle DB Page.
