### ISSUE TITLE
Databases Page > Oracle

### ISSUE THREAD

**Issue by andreafurla** [ercole-io/ercole-web#281]
UI
follow the design

![Schermata 2021-04-01 alle 11 14 44](https://user-images.githubusercontent.com/19222614/113693298-bcce5400-96ce-11eb-95df-0306a365d485.png)

Also (like the filters buttons of the "Hosts page"):
- group Archivelog Mode, DR and HA in a block colums and show it after click on a button called "Reliability";
- group Datafile (GB) and Segment (GB) in a block colums and show it after click on a button called "Space used";
- toggle Charset column with a button called "Charset".

UX
As a user when I view the Oracle table, If I click on Show more info: RELIABILITY, then I must be able to view all related columns straight after the first column "DB Name",
If I click on Show more info: SPACE USED, then the view must be updated and I must be able to view all related columns straight after the first column "DB Name",
The first columns db name will always be fixed,
While the other columns will be dynamically displayed based on the selected button Show more

**Comment by anbrenna** [comment]
Please verify these items:
- columns order
- delete Size word from columns name

**Comment by anbrenna** [comment]
Verify these items:
- columns order
- Delete "Size" word from columns name
