### ISSUE TITLE
Update the Info section in Hosts/MySql page 

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole-web#290]
Insert groups in the info section in order to show better the data in the page

**Comment by rcmaiolini** [comment]
DB Details
DB Name
Version
Platform
Architecture
Edition
Engine

MEMORY
Sort Buffer Size
Log Buffer Size
Pool Buffer Size

ADDITIONAL INFO
Read Only
Read Only log enabled
Threads concurrency
Server Charset
System Charset
Page Size
