### ISSUE TITLE
Keep more infos open

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-web#339]
**Is your feature request related to a problem? Please describe.**
When I need some info hidden in the more infos menus and I change page I need to reopen them every time. 
![image.png](https://images.zenhubusercontent.com/57125f2bbf93871ccd998aa1/22596296-3b45-434e-9753-21c70935268b)

**Describe the solution you'd like**
The FE must keep memory of what I choose to visualize and keep them open accordingly.

**Comment by anbrenna** [comment]
Already done.
