### ISSUE TITLE
Improve open values on lists

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-web#430]
**Is your feature request related to a problem? Please describe.**
It's difficult to understand when a value isn't opened because you are clicking on a text value on a line.

**Describe the solution you'd like**
The entire line should let you open the value and redirect in the detail instead of select the text.

**Additional context**
E.g.:
![image](https://user-images.githubusercontent.com/1636493/150799731-2ccde4c6-ce5c-4a1b-8fe1-1e74a9313fc2.png)

**Comment by anbrenna** [comment]
Solved by https://github.com/ercole-io/ercole-web/issues/451
