### ISSUE TITLE
Licenses Used and Host detail: cross out Used Licenses value if Cluster Licenses value more than zero

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-web#464]
**Is your feature request related to a problem? Please describe.**
If there's a Cluster License value, the Used License value isn't "valid" anymore, I want to make this more clear.

**Describe the solution you'd like**
Licenses Used and Host detail: cross out Used Licenses value if Cluster Licenses value more than zero

**Comment by anbrenna** [comment]
Modify also Licenses used per hosts
