### ISSUE TITLE
Add patch pages

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole-web#558]
Create a new menu item under Oracle Databases
Api: /hosts/technologies/oracle/databases/patch-list

**Comment by raffaelloferrari** [comment]
Query Mongo:
db = db.getSiblingDB('ercole')
print("Hostname|DB Name|Version|Patch ID|Action|Description|Date");
db.hosts.aggregate([{$match: {
 archived: false
}}, {$unwind: {
 path: '$features.oracle.database.databases'
}}, {$set: {
 database: '$features.oracle.database.databases'
}}, {$unwind: {
 path: '$database.patches'
}}, {$project: {
 hostname: '$hostname',
 dbname: '$database.name',
 patches: '$database.patches'
}}]).forEach(function(patch){
  print(patch.hostname+"|"+patch.dbname+"|"+patch.patches.version
      +"|"+patch.patches.patchID+"|"+patch.patches.action+"|"+patch.patches.description
      +"|"+patch.patches.date);
});
